---
- name: Create Jenkins home directory
  file:
    path: /opt/jenkins
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Create init.groovy.d directory
  file:
    path: /opt/jenkins/init.groovy.d
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"

- name: Copy admin groovy script
  copy:
    src: create_admin.groovy
    dest: /opt/jenkins/init.groovy.d/create_admin.groovy
  notify: restart jenkins

- name: Copy plugins list
  copy:
    src: plugins.txt
    dest: /opt/jenkins/plugins.txt
  notify: restart jenkins

- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /opt/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

- name: Install Jenkins plugins (ONE TIME)
  command: >
    docker exec jenkins
    jenkins-plugin-cli --plugin-file /var/jenkins_home/plugins.txt
  args:
    creates: /opt/jenkins/plugins/git.jpi
  notify: restart jenkins
