---
- name: Create SonarQube directories
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0755"
  loop:
    - /opt/sonar/data
    - /opt/sonar/extensions

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:lts
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes:
      - /opt/sonar/data:/opt/sonarqube/data
      - /opt/sonar/extensions:/opt/sonarqube/extensions
